[package]
name = "kernel"
version = "0.1.0"
authors = ["Michael Spencer <sonrisesoftware@gmail.com>"]
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "0.7.0"
multiboot2 = "*"
rlibc = "*"
spin = "*"
volatile = "*"

[dependencies.x86]
version = "*"
default-features = false
