[package]
authors = ["Michael Spencer <sonrisesoftware@gmail.com>"]
name = "kernel"
publish = false
version = "0.1.0"

[dependencies]
bitflags = "0.7.0"
linked_list_allocator = "0.2.3"
multiboot2 = "*"
once = "0.3"
rlibc = "*"
spin = "*"
volatile = "*"

[dependencies.x86]
default-features = false
version = "*"

[dependencies.alloc_kernel]
path = "../alloc_kernel"

[lib]
crate-type = ["staticlib"]
